version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: banner_service
      POSTGRES_PASSWORD: bs1234
      POSTGRES_DB: banners
    ports:
      - "5432:5432"
    volumes:
      - C:\Docker\pgdev:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - C:\Docker\redisdev:/data
